source 'https://github.com/CocoaPods/Specs.git'

target 'SpooferDemo' do
  platform :ios, '12.0'
  use_frameworks!

  pod 'SwiftGen', '~> 6.0.0'
  pod 'Realm', '3.21.0'
  pod 'RealmSwift', '3.21.0'
  pod 'NetworkResponseSpoofer', :path => "../"
  pod 'NetworkResponseSpoofer/SpooferUI', :path => "../"
end

# target 'SpooferDemo_Mac' do
#   platform :osx, '10.12'
#   use_frameworks!

#   pod 'NetworkResponseSpoofer/Core', :path => "../"
# end
