source 'https://github.com/CocoaPods/Specs.git'

target 'SpooferDemo' do
  platform :ios, '10.0'
  use_frameworks!

  pod 'NetworkResponseSpoofer', :path => "../"
  pod 'NetworkResponseSpoofer/SpooferUI', :path => "../"
end

target 'SpooferDemo_Mac' do
  platform :osx, '10.11'
  use_frameworks!

  pod 'NetworkResponseSpoofer', :path => "../"
end
